meta_name: "Quand La Vie C'est Pourri"
meta_title: "Quand La Vie C'est Pourri - Fini les journées de merde!"
meta_description: "Parfois on passe des journées de merde et faire un truc qui nous plait pourrait nous aider à sortir de cette spirale de caca... Tirez une carte pour apporter du kiffe dans votre vie!"
meta_image: "QLVCP_background.jpg" # should exist in `app/assets/images/`
